/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.lukekuza.calcsketchpad.gui;

import com.lukekuza.calcsketchpad.util.SharedDataUtil;

import javax.swing.*;

/**
 * @author User
 */
public class ChartGUI extends javax.swing.JFrame {

    DefaultListModel listModel = new DefaultListModel();
    DefaultListModel dydxListModel = new DefaultListModel();
    DefaultListModel yListModel = new DefaultListModel();
    // Variables declaration - do not modify
    private javax.swing.JList dydxList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList xList;
    private javax.swing.JList yList;

    /**
     * Creates new form ChartGUI
     */
    public ChartGUI() {
        initComponents();
    }

    public static void invokeGUI() {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SharedDataUtil sharedDataUtil = SharedDataUtil.getInstance();

                ChartGUI gui = new ChartGUI();
                gui.setLocation(500, 100);

                DefaultListModel model = (DefaultListModel) gui.xList.getModel();
                Double[] xVals = sharedDataUtil.getBundle().get("xVals");

                for (double x : xVals)
                    model.addElement(x);

                model = (DefaultListModel) gui.yList.getModel();
                Double[] yVals = sharedDataUtil.getBundle().get("yVals");

                for (double y : yVals)
                    model.addElement(y);

                model = (DefaultListModel) gui.dydxList.getModel();
                Double[] dydx = sharedDataUtil.getBundle().get("dydx");

                for (double dydxVal : dydx)
                    model.addElement(dydxVal);

                gui.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        dydxList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        yList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chart");

        jLabel1.setText("x");

        jLabel2.setText("dy/dx");

        jLabel3.setText("y");

        xList.setModel(listModel);
        jScrollPane1.setViewportView(xList);

        dydxList.setModel(dydxListModel);
        jScrollPane2.setViewportView(dydxList);

        yList.setModel(yListModel);
        jScrollPane3.setViewportView(yList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel2)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>
    // End of variables declaration                   
}